### ISSUE TITLE
CT phetioID missing from the baseline that was not an archetype

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#105]
```
density : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1634710527841%22%2C%22timestamp%22%3A1634712122449%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: density.introScreen.view.blockAControlPanel.comboBoxMaterialProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: density.introScreen.view.blockAControlPanel.comboBoxMaterialProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/phet-io/js/phetioEngine.js:334:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:279:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:191:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:353:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/joist/js/Sim.js:823:57
id: Bayes Chrome
Snapshot from 10/20/2021, 12:15:27 AM

----------------------------------

density : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/phet-io-wrappers/mirror-inputs/?sim=density&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1634710527841%22%2C%22timestamp%22%3A1634719172942%7D
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: density.introScreen.view.blockAControlPanel.comboBoxMaterialProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: density.introScreen.view.blockAControlPanel.comboBoxMaterialProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/phet-io/js/phetioEngine.js:334:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:279:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:191:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:353:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/joist/js/Sim.js:823:57
id: Bayes Chrome
Snapshot from 10/20/2021, 12:15:27 AM

----------------------------------

density : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/studio/?sim=density&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1634710527841%22%2C%22timestamp%22%3A1634711974575%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
density.introScreen.view.blockAControlPanel.comboBoxMaterialProperty: 3. Any schema entries in the overrides file must exist in the baseline file.
Error: Assertion failed: PhET-iO API error:
density.introScreen.view.blockAControlPanel.comboBoxMaterialProperty: 3. Any schema entries in the overrides file must exist in the baseline file.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/assert/js/assert.js:25:13)
at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:228:15)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:176:16)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/phet-io/js/phetioEngine.js:334:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:279:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:191:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:353:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/joist/js/Sim.js:823:57
id: Bayes Chrome
Snapshot from 10/20/2021, 12:15:27 AM

----------------------------------

density : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/phet-io-wrappers/phet-io-wrappers-tests.html?sim=density&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: density: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: density.introScreen.view.blockAControlPanel.comboBoxMaterialProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: density.introScreen.view.blockAControlPanel.comboBoxMaterialProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/phet-io/js/phetioEngine.js:334:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:279:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:191:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:353:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/joist/js/Sim.js:823:57

Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: density.introScreen.view.blockAControlPanel.comboBoxMaterialPropertyError: Assertion failed: phetioID missing from the baseline that was not an archetype: density.introScreen.view.blockAControlPanel.comboBoxMaterialProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/phet-io/js/phetioEngine.js:334:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:279:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:191:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:353:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/joist/js/Sim.js:823:57
id: Bayes Chrome
Snapshot from 10/20/2021, 12:15:27 AM

----------------------------------

density : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/phet-io-wrappers/phet-io-wrappers-tests.html?sim=density
3 out of 4 tests passed. 1 failed.
SimTests: density: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: density.introScreen.view.blockAControlPanel.comboBoxMaterialProperty
Error: Assertion failed: phetioID missing from the baseline that was not an archetype: density.introScreen.view.blockAControlPanel.comboBoxMaterialProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/phet-io/js/phetioEngine.js:334:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:279:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:191:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:353:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/joist/js/Sim.js:823:57

Uncaught Error: Uncaught Error: Assertion failed: phetioID missing from the baseline that was not an archetype: density.introScreen.view.blockAControlPanel.comboBoxMaterialPropertyError: Assertion failed: phetioID missing from the baseline that was not an archetype: density.introScreen.view.blockAControlPanel.comboBoxMaterialProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/assert/js/assert.js:25:13)
at PhetioAPIValidation.validateOverridesFile (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:172:19)
at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/tandem/js/phetioAPIValidation.js:91:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/phet-io/js/phetioEngine.js:334:29
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/TinyEmitter.js:86:9)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:279:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:191:14)
at Property.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/axon/js/Property.js:353:32)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1634710527841/joist/js/Sim.js:823:57
id: Bayes Chrome
Snapshot from 10/20/2021, 12:15:27 AM
```

**Comment by jonathanolson** [comment]
This last error seems to be happening in multitouch-only fuzzing situations. It's taken a good chunk of time to try to figure out, and I still don't have a good handle on it.

@arouinfar and @kathy-phet, I'm curious how much more time this is worth. I'd consider seeing if QA can reproduce the error with multitouch testing (it looks like Compare screen, messing with sliders will dragging masses MAY be a likely way to reproduce). Thoughts?

**Comment by arouinfar** [comment]
> I'd consider seeing if QA can reproduce the error with multitouch testing (it looks like Compare screen, messing with sliders will dragging masses MAY be a likely way to reproduce). Thoughts?

That sounds like a good approach @jonathanolson. If QA is unable to recreate the error, it's likely not a critical fix. And if QA is able to reproduce, we may have more information about how to actually address it.

**Comment by KatieWoe** [comment]
I managed to reproduce this on Master.
1. Go to the first screen
2. Turn on the second block
3. Hold the second block with one finger
4. With the second finger, switch back to one block.
5. The second block sticks around and the errors pile up until you let go of the block. Sim seems to behave normally after.

**Comment by jonathanolson** [comment]
I believe the above patch should fix that (and I'm now fuzzing without errors). Can you verify? (I don't have a multitouch device besides my phone, hard to evaluate errors).

**Comment by KatieWoe** [comment]
Looks fixed on master
