### ISSUE TITLE
CT value failed isValidValue

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#122]
```
density : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638897131278/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1638897131278%22%2C%22timestamp%22%3A1638900911729%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: value failed isValidValue: 0.4
Error: Assertion failed: value failed isValidValue: 0.4
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638897131278/assert/js/assert.js:25:13)
at Object.isValueValid (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638897131278/chipper/dist/js/axon/js/ValidatorDef.js:299:39)
at validate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638897131278/chipper/dist/js/axon/js/validate.js:33:18)
at NumberProperty.validateNumberAndRangeProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638897131278/chipper/dist/js/axon/js/NumberProperty.js:102:9)
at NumberProperty.validateNumberProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638897131278/chipper/dist/js/axon/js/NumberProperty.js:245:14)
at rangePropertyObserver (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638897131278/chipper/dist/js/axon/js/NumberProperty.js:118:51)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638897131278/chipper/dist/js/axon/js/TinyEmitter.js:69:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638897131278/chipper/dist/js/axon/js/Property.js:228:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638897131278/chipper/dist/js/axon/js/Property.js:159:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1638897131278/chipper/dist/js/axon/js/DerivedProperty.js:92:13)
id: Bayes Chrome
Snapshot from 12/7/2021, 10:12:11 AM
```

**Comment by jonathanolson** [comment]
I haven't been able to reproduce. This looks like it might be in a range that's fixed, but I'm not sure. I'll leave open for now.

**Comment by KatieWoe** [comment]
Ran for several minutes in dev.20 in debug version with `?fuzz`. Did not see. Will leave open just in case.

**Comment by KatieWoe** [comment]
Ran for several minutes in the rc.3 debug version with `?fuzz`. Closing
