### ISSUE TITLE
CT Missing string information for density-buoyancy-common newtonsPatternProperty.lazyLink

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#144]
```
density : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> tsc complete: 103320ms
Building runnable repository (density, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 28873ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Missing string information for density-buoyancy-common newtonsPatternProperty.lazyLink
at /data/share/phet/continuous-testing/ct-snapshots/1661305124647/chipper/js/grunt/getStringMap.js:213:11
at Array.forEach (<anonymous>)
at /data/share/phet/continuous-testing/ct-snapshots/1661305124647/chipper/js/grunt/getStringMap.js:201:15
at Array.forEach (<anonymous>)
at /data/share/phet/continuous-testing/ct-snapshots/1661305124647/chipper/js/grunt/getStringMap.js:200:23
at Array.forEach (<anonymous>)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1661305124647/chipper/js/grunt/getStringMap.js:153:24)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1661305124647/chipper/js/grunt/buildRunnable.js:138:21)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
Full Error details:
AssertionError [ERR_ASSERTION]: Missing string information for density-buoyancy-common newtonsPatternProperty.lazyLink
Snapshot from 8/23/2022, 7:38:44 PM

----------------------------------

density : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661305124647%22%2C%22timestamp%22%3A1661312133699%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

density.compareScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.8660253438317398,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.86602534383174,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.introScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.4765727289473771,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.47657272894737723,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.mysteryScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.8660253438317398,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.86602534383174,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.mysteryScreen.model.scale._data.initialState differs.
Expected:
{"canMove":false,"canRotate":false,"force":{"x":0,"y":0},"massShape":"BLOCK","matrix":{"entries":[1,0,0,0,1,0,-0.7410253438317398,0.03,1],"type":"TRANSLATION_2D"},"originalMatrix":{"entries":[1,0,0,0,1,0,-0.7410253438317398,0.03,1],"type":"TRANSLATION_2D"},"position":{"x":-0.7410253524780274,"y":0.030000001192092896},"stepMatrix":{"entries":[1,0,0,0,1,0,0,0,1],"type":"IDENTITY"},"tag":"NONE","velocity":{"x":0,"y":0}}
actual:
{"matrix":{"entries":[1,0,0,0,1,0,-0.74102534383174,0.03,1],"type":"TRANSLATION_2D"},"stepMatrix":{"entries":[1,0,0,0,1,0,0,0,1],"type":"IDENTITY"},"originalMatrix":{"entries":[1,0,0,0,1,0,-0.74102534383174,0.03,1],"type":"TRANSLATION_2D"},"canRotate":false,"canMove":false,"tag":"NONE","massShape":"BLOCK","position":{"x":-0.7410253524780274,"y":0.030000001192092896},"velocity":{"x":0,"y":0},"force":{"x":0,"y":0}}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:365:22)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM

----------------------------------

density : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661305124647%22%2C%22timestamp%22%3A1661318275289%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

density.compareScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.8660253438317398,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.86602534383174,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.introScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.4765727289473771,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.47657272894737723,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.mysteryScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.8660253438317398,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.86602534383174,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.mysteryScreen.model.scale._data.initialState differs.
Expected:
{"canMove":false,"canRotate":false,"force":{"x":0,"y":0},"massShape":"BLOCK","matrix":{"entries":[1,0,0,0,1,0,-0.7410253438317398,0.03,1],"type":"TRANSLATION_2D"},"originalMatrix":{"entries":[1,0,0,0,1,0,-0.7410253438317398,0.03,1],"type":"TRANSLATION_2D"},"position":{"x":-0.7410253524780274,"y":0.030000001192092896},"stepMatrix":{"entries":[1,0,0,0,1,0,0,0,1],"type":"IDENTITY"},"tag":"NONE","velocity":{"x":0,"y":0}}
actual:
{"matrix":{"entries":[1,0,0,0,1,0,-0.74102534383174,0.03,1],"type":"TRANSLATION_2D"},"stepMatrix":{"entries":[1,0,0,0,1,0,0,0,1],"type":"IDENTITY"},"originalMatrix":{"entries":[1,0,0,0,1,0,-0.74102534383174,0.03,1],"type":"TRANSLATION_2D"},"canRotate":false,"canMove":false,"tag":"NONE","massShape":"BLOCK","position":{"x":-0.7410253524780274,"y":0.030000001192092896},"velocity":{"x":0,"y":0},"force":{"x":0,"y":0}}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:365:22)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM

----------------------------------

density : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1661305124647%22%2C%22timestamp%22%3A1661334551851%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

density.compareScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.8660253438317398,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.86602534383174,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.introScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.4765727289473771,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.47657272894737723,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.mysteryScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.8660253438317398,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.86602534383174,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.mysteryScreen.model.scale._data.initialState differs.
Expected:
{"canMove":false,"canRotate":false,"force":{"x":0,"y":0},"massShape":"BLOCK","matrix":{"entries":[1,0,0,0,1,0,-0.7410253438317398,0.03,1],"type":"TRANSLATION_2D"},"originalMatrix":{"entries":[1,0,0,0,1,0,-0.7410253438317398,0.03,1],"type":"TRANSLATION_2D"},"position":{"x":-0.7410253524780274,"y":0.030000001192092896},"stepMatrix":{"entries":[1,0,0,0,1,0,0,0,1],"type":"IDENTITY"},"tag":"NONE","velocity":{"x":0,"y":0}}
actual:
{"matrix":{"entries":[1,0,0,0,1,0,-0.74102534383174,0.03,1],"type":"TRANSLATION_2D"},"stepMatrix":{"entries":[1,0,0,0,1,0,0,0,1],"type":"IDENTITY"},"originalMatrix":{"entries":[1,0,0,0,1,0,-0.74102534383174,0.03,1],"type":"TRANSLATION_2D"},"canRotate":false,"canMove":false,"tag":"NONE","massShape":"BLOCK","position":{"x":-0.7410253524780274,"y":0.030000001192092896},"velocity":{"x":0,"y":0},"force":{"x":0,"y":0}}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1661305124647/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:365:22)
id: Bayes Puppeteer
Snapshot from 8/23/2022, 7:38:44 PM
```

**Comment by jonathanolson** [comment]
I believe the *StringProperty work should have handled the top bug, and the others are going to be handled in another issue.
