### ISSUE TITLE
CT Cannot read properties of null (reading '_frameId')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#146]
```
density : fuzz : built-phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/density/build/phet-io/density_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1663254326391%22%2C%22timestamp%22%3A1663274746497%7D&fuzz&memoryLimit=1000&phetioStandalone
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read properties of null (reading '_frameId')
TypeError: Cannot read properties of null (reading '_frameId')
at e.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/density/build/phet-io/density_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1663254326391%22%2C%22timestamp%22%3A1663274746497%7D&fuzz&memoryLimit=1000&phetioStandalone:1068:1166098)
at e.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/density/build/phet-io/density_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1663254326391%22%2C%22timestamp%22%3A1663274746497%7D&fuzz&memoryLimit=1000&phetioStandalone:1068:1165907)
at e.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/density/build/phet-io/density_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1663254326391%22%2C%22timestamp%22%3A1663274746497%7D&fuzz&memoryLimit=1000&phetioStandalone:1068:1184503)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/density/build/phet-io/density_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1663254326391%22%2C%22timestamp%22%3A1663274746497%7D&fuzz&memoryLimit=1000&phetioStandalone:1068:1721152)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/density/build/phet-io/density_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1663254326391%22%2C%22timestamp%22%3A1663274746497%7D&fuzz&memoryLimit=1000&phetioStandalone:1068:2818761)
at n (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/density/build/phet-io/density_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1663254326391%22%2C%22timestamp%22%3A1663274746497%7D&fuzz&memoryLimit=1000&phetioStandalone:1068:26666)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/density/build/phet-io/density_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1663254326391%22%2C%22timestamp%22%3A1663274746497%7D&fuzz&memoryLimit=1000&phetioStandalone:1068:41845)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/density/build/phet-io/density_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1663254326391%22%2C%22timestamp%22%3A1663274746497%7D&fuzz&memoryLimit=1000&phetioStandalone:1068:35072)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/density/build/phet-io/density_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1663254326391%22%2C%22timestamp%22%3A1663274746497%7D&fuzz&memoryLimit=1000&phetioStandalone:1068:34470)
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/density/build/phet-io/density_all_phet-io.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22fuzz%22%2C%22built-phet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1663254326391%22%2C%22timestamp%22%3A1663274746497%7D&fuzz&memoryLimit=1000&phetioStandalone:1068:34252)
id: Bayes Puppeteer
Snapshot from 9/15/2022, 9:05:26 AM

----------------------------------

density : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1663254326391%22%2C%22timestamp%22%3A1663262342949%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

density.compareScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.8660253438317398,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.86602534383174,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.introScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.47648041051542245,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.47648041051542256,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.mysteryScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.8660253438317398,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.86602534383174,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.mysteryScreen.model.scale._data.initialState differs.
Expected:
{"canMove":false,"canRotate":false,"force":{"x":0,"y":0},"massShape":"BLOCK","matrix":{"entries":[1,0,0,0,1,0,-0.7410253438317398,0.03,1],"type":"TRANSLATION_2D"},"originalMatrix":{"entries":[1,0,0,0,1,0,-0.7410253438317398,0.03,1],"type":"TRANSLATION_2D"},"position":{"x":-0.7410253524780274,"y":0.030000001192092896},"stepMatrix":{"entries":[1,0,0,0,1,0,0,0,1],"type":"IDENTITY"},"tag":"NONE","velocity":{"x":0,"y":0}}
actual:
{"matrix":{"entries":[1,0,0,0,1,0,-0.74102534383174,0.03,1],"type":"TRANSLATION_2D"},"stepMatrix":{"entries":[1,0,0,0,1,0,0,0,1],"type":"IDENTITY"},"originalMatrix":{"entries":[1,0,0,0,1,0,-0.74102534383174,0.03,1],"type":"TRANSLATION_2D"},"canRotate":false,"canMove":false,"tag":"NONE","massShape":"BLOCK","position":{"x":-0.7410253524780274,"y":0.030000001192092896},"velocity":{"x":0,"y":0},"force":{"x":0,"y":0}}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:365:22)
id: Bayes Puppeteer
Snapshot from 9/15/2022, 9:05:26 AM

----------------------------------

density : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1663254326391%22%2C%22timestamp%22%3A1663267498826%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

density.compareScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.8660253438317398,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.86602534383174,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.introScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.47648041051542245,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.47648041051542256,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.mysteryScreen.model.invisibleBarrierBoundsProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":{"maxX":0.8660253438317398,"maxY":4,"maxZ":0.2,"minX":-0.8660253438317398,"minY":-4,"minZ":-0.2}}
actual:
{"value":{"minX":-0.86602534383174,"minY":-4,"minZ":-0.2,"maxX":0.86602534383174,"maxY":4,"maxZ":0.2},"validValues":null,"units":null}

density.mysteryScreen.model.scale._data.initialState differs.
Expected:
{"canMove":false,"canRotate":false,"force":{"x":0,"y":0},"massShape":"BLOCK","matrix":{"entries":[1,0,0,0,1,0,-0.7410253438317398,0.03,1],"type":"TRANSLATION_2D"},"originalMatrix":{"entries":[1,0,0,0,1,0,-0.7410253438317398,0.03,1],"type":"TRANSLATION_2D"},"position":{"x":-0.7410253524780274,"y":0.030000001192092896},"stepMatrix":{"entries":[1,0,0,0,1,0,0,0,1],"type":"IDENTITY"},"tag":"NONE","velocity":{"x":0,"y":0}}
actual:
{"matrix":{"entries":[1,0,0,0,1,0,-0.74102534383174,0.03,1],"type":"TRANSLATION_2D"},"stepMatrix":{"entries":[1,0,0,0,1,0,0,0,1],"type":"IDENTITY"},"originalMatrix":{"entries":[1,0,0,0,1,0,-0.74102534383174,0.03,1],"type":"TRANSLATION_2D"},"canRotate":false,"canMove":false,"tag":"NONE","massShape":"BLOCK","position":{"x":-0.7410253524780274,"y":0.030000001192092896},"velocity":{"x":0,"y":0},"force":{"x":0,"y":0}}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1663254326391/assert/js/assert.js:28:13)
at assert (phetioEngine.ts:365:22)
id: Bayes Puppeteer
Snapshot from 9/15/2022, 9:05:26 AM
```

**Comment by jonathanolson** [comment]
Thanks! I believe this should be handled with the above commit.
