### ISSUE TITLE
CT required tandems must be supplie

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#173]
```
density : phet-io-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1683628485262%22%2C%22timestamp%22%3A1683629071388%7D&ea&brand=phet-io&phetioStandalone&fuzz
Query: ea&brand=phet-io&phetioStandalone&fuzz
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:199:16)
at initializePhetioObject (Node.ts:6325:10)
at initializePhetioObject (Text.ts:227:10)
at initializePhetioObject (Node.ts:6315:9)
at mutate (Text.ts:134:17)
at mutate (Text.ts:124:9)
at (TextPushButton.ts:45:17)
at (ContextLossFailureDialog.ts:59:19)
at (ThreeStage.ts:262:31)
id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:34:45 AM

----------------------------------

density : phet-io-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1683628485262%22%2C%22timestamp%22%3A1683630251993%7D&ea&brand=phet-io&phetioStandalone&fuzz
Query: ea&brand=phet-io&phetioStandalone&fuzz
Uncaught TypeError: Cannot read properties of null (reading 'hideWithoutReload')
TypeError: Cannot read properties of null (reading 'hideWithoutReload')
at hideWithoutReload (ThreeStage.ts:98:30)
id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:34:45 AM

----------------------------------

density : phet-io-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1683628485262%22%2C%22timestamp%22%3A1683636560258%7D&ea&brand=phet-io&phetioStandalone&fuzz
Query: ea&brand=phet-io&phetioStandalone&fuzz
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/assert/js/assert.js:28:13)
at assert (PhetioObject.ts:199:16)
at initializePhetioObject (Node.ts:6325:10)
at initializePhetioObject (Text.ts:227:10)
at initializePhetioObject (Node.ts:6315:9)
at mutate (Text.ts:134:17)
at mutate (Text.ts:124:9)
at (TextPushButton.ts:45:17)
at (ContextLossFailureDialog.ts:59:19)
at (ThreeStage.ts:262:31)
id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:34:45 AM

----------------------------------

density : phet-io-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1683628485262%22%2C%22timestamp%22%3A1683638851999%7D&ea&brand=phet-io&phetioStandalone&fuzz
Query: ea&brand=phet-io&phetioStandalone&fuzz
Uncaught TypeError: Cannot read properties of null (reading 'hideWithoutReload')
TypeError: Cannot read properties of null (reading 'hideWithoutReload')
at hideWithoutReload (ThreeStage.ts:98:30)
id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:34:45 AM

----------------------------------

density : phet-io-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1683628485262%22%2C%22timestamp%22%3A1683640812583%7D&ea&brand=phet-io&phetioStandalone&fuzz
Query: ea&brand=phet-io&phetioStandalone&fuzz
Uncaught TypeError: Cannot read properties of null (reading 'hideWithoutReload')
TypeError: Cannot read properties of null (reading 'hideWithoutReload')
at hideWithoutReload (ThreeStage.ts:98:30)
id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:34:45 AM

----------------------------------

density : phet-io-fuzz : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1683628485262%22%2C%22timestamp%22%3A1683652315469%7D&ea&brand=phet-io&phetioStandalone&fuzz
Query: ea&brand=phet-io&phetioStandalone&fuzz
Uncaught TypeError: Cannot read properties of null (reading 'hideWithoutReload')
TypeError: Cannot read properties of null (reading 'hideWithoutReload')
at hideWithoutReload (ThreeStage.ts:98:30)
id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:34:45 AM

----------------------------------

density : phet-io-wrappers-tests : assert
http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/phet-io-wrappers/phet-io-wrappers-tests.html?sim=density&phetioDebug=true&phetioWrapperDebug=true
12 out of 13 tests passed. 1 failed.
SimTests: density: iframe API failed:
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/assert/js/assert.js:28:13)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5825:11)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:187:11)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5815:10)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:97:18)
at new Text (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:89:10)
at new TextPushButton (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/sun/js/buttons/TextPushButton.js:26:18)
at new ContextLossFailureDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery-phet/js/ContextLossFailureDialog.js:39:20)
at ThreeStage.showContextLossDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/mobius/js/ThreeStage.js:207:32)

SimTests: density: iframe API failed:
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/assert/js/assert.js:28:13)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5825:11)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:187:11)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5815:10)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:97:18)
at new Text (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:89:10)
at new TextPushButton (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/sun/js/buttons/TextPushButton.js:26:18)
at new ContextLossFailureDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery-phet/js/ContextLossFailureDialog.js:39:20)
at ThreeStage.showContextLossDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/mobius/js/ThreeStage.js:207:32)

SimTests: density: iframe API failed:
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/assert/js/assert.js:28:13)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5825:11)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:187:11)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5815:10)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:97:18)
at new Text (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:89:10)
at new TextPushButton (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/sun/js/buttons/TextPushButton.js:26:18)
at new ContextLossFailureDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery-phet/js/ContextLossFailureDialog.js:39:20)
at ThreeStage.showContextLossDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/mobius/js/ThreeStage.js:207:32)

id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:34:45 AM

----------------------------------

density : phet-io-wrappers-tests : no-assert
http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/phet-io-wrappers/phet-io-wrappers-tests.html?sim=density
12 out of 13 tests passed. 1 failed.
SimTests: density: iframe API failed:
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/assert/js/assert.js:28:13)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5825:11)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:187:11)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5815:10)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:97:18)
at new Text (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:89:10)
at new TextPushButton (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/sun/js/buttons/TextPushButton.js:26:18)
at new ContextLossFailureDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery-phet/js/ContextLossFailureDialog.js:39:20)
at ThreeStage.showContextLossDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/mobius/js/ThreeStage.js:207:32)

SimTests: density: iframe API failed:
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/assert/js/assert.js:28:13)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5825:11)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:187:11)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5815:10)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:97:18)
at new Text (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:89:10)
at new TextPushButton (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/sun/js/buttons/TextPushButton.js:26:18)
at new ContextLossFailureDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery-phet/js/ContextLossFailureDialog.js:39:20)
at ThreeStage.showContextLossDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/mobius/js/ThreeStage.js:207:32)

SimTests: density: iframe API failed:
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/assert/js/assert.js:28:13)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5825:11)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:187:11)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5815:10)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:97:18)
at new Text (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:89:10)
at new TextPushButton (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/sun/js/buttons/TextPushButton.js:26:18)
at new ContextLossFailureDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery-phet/js/ContextLossFailureDialog.js:39:20)
at ThreeStage.showContextLossDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/mobius/js/ThreeStage.js:207:32)

SimTests: density: iframe API failed:
Uncaught TypeError: Cannot read properties of null (reading 'hideWithoutReload')
TypeError: Cannot read properties of null (reading 'hideWithoutReload')
at HTMLCanvasElement.<anonymous> (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/mobius/js/ThreeStage.js:66:30)

SimTests: density: iframe API failed:
Uncaught TypeError: Cannot read properties of null (reading 'hideWithoutReload')
TypeError: Cannot read properties of null (reading 'hideWithoutReload')
at HTMLCanvasElement.<anonymous> (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/mobius/js/ThreeStage.js:66:30)

SimTests: density: iframe API failed:
Uncaught TypeError: Cannot read properties of null (reading 'hideWithoutReload')
TypeError: Cannot read properties of null (reading 'hideWithoutReload')
at HTMLCanvasElement.<anonymous> (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/mobius/js/ThreeStage.js:66:30)

id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:34:45 AM

----------------------------------

density : phet-io-wrappers-tests : no-assert
http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/phet-io-wrappers/phet-io-wrappers-tests.html?sim=density
12 out of 13 tests passed. 1 failed.
SimTests: density: iframe API failed:
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/assert/js/assert.js:28:13)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5825:11)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:187:11)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5815:10)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:97:18)
at new Text (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:89:10)
at new TextPushButton (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/sun/js/buttons/TextPushButton.js:26:18)
at new ContextLossFailureDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery-phet/js/ContextLossFailureDialog.js:39:20)
at ThreeStage.showContextLossDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/mobius/js/ThreeStage.js:207:32)

SimTests: density: iframe API failed:
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/assert/js/assert.js:28:13)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5825:11)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:187:11)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5815:10)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:97:18)
at new Text (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:89:10)
at new TextPushButton (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/sun/js/buttons/TextPushButton.js:26:18)
at new ContextLossFailureDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery-phet/js/ContextLossFailureDialog.js:39:20)
at ThreeStage.showContextLossDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/mobius/js/ThreeStage.js:207:32)

SimTests: density: iframe API failed:
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/assert/js/assert.js:28:13)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/tandem/js/PhetioObject.js:135:17)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5825:11)
at Text.initializePhetioObject (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:187:11)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Node.js:5815:10)
at Text.mutate (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:97:18)
at new Text (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery/js/nodes/Text.js:89:10)
at new TextPushButton (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/sun/js/buttons/TextPushButton.js:26:18)
at new ContextLossFailureDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/scenery-phet/js/ContextLossFailureDialog.js:39:20)
at ThreeStage.showContextLossDialog (http://127.0.0.1/continuous-testing/ct-snapshots/1683628485262/chipper/dist/js/mobius/js/ThreeStage.js:207:32)

id: Sparky Puppeteer
Snapshot from 5/9/2023, 4:34:45 AM
```

**Comment by jonathanolson** [comment]
I believe I've handled the issues, but leaving open to see.

**Comment by jonathanolson** [comment]
Looks fixed on sparky, @KatieWoe can you verify?
