### ISSUE TITLE
CT never heard back from upstream sim, likely there was a problem getting state.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#186]
```
density : migration : 1.1->main
http://128.138.93.172/continuous-testing/ct-snapshots/1697646964071/phet-io-wrappers/migration/?sim=density&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&oldVersion=1.1&migrationRate=5000&wrapperContinuousTest=%7B%22test%22%3A%5B%22density%22%2C%22migration%22%2C%221.1-%3Emain%22%5D%2C%22snapshotName%22%3A%22snapshot-1697646964071%22%2C%22timestamp%22%3A1697647279704%7D
Assertion failed: never heard back from upstream sim, likely there was a problem getting state.
Error: Assertion failed: never heard back from upstream sim, likely there was a problem getting state.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1697646964071/assert/js/assert.js:28:13)
at <unknown> (http://128.138.93.172/continuous-testing/ct-snapshots/1697646964071/phet-io-wrappers/migration/migration.js:221:23)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1697646964071%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Ddensity%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26oldVersion%3D1.1%26migrationRate%3D5000&duration=80000&testInfo=%7B%22test%22%3A%5B%22density%22%2C%22migration%22%2C%221.1-%3Emain%22%5D%2C%22snapshotName%22%3A%22snapshot-1697646964071%22%2C%22timestamp%22%3A1697647279704%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1697646964071%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Ddensity%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26oldVersion%3D1.1%26migrationRate%3D5000&duration=80000&testInfo=%7B%22test%22%3A%5B%22density%22%2C%22migration%22%2C%221.1-%3Emain%22%5D%2C%22snapshotName%22%3A%22snapshot-1697646964071%22%2C%22timestamp%22%3A1697647279704%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1697646964071/phet-io-wrappers/migration/?sim=density&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&oldVersion=1.1&migrationRate=5000&wrapperContinuousTest=%7B%22test%22%3A%5B%22density%22%2C%22migration%22%2C%221.1-%3Emain%22%5D%2C%22snapshotName%22%3A%22snapshot-1697646964071%22%2C%22timestamp%22%3A1697647279704%7D
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1697646964071/studio/?sim=density&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22density%22,%22migration%22,%221.1-%3Emain%22],%22snapshotName%22:%22snapshot-1697646964071%22,%22timestamp%22:1697647279704}&locales=*
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1697646964071/density/density_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=density&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22density%22,%22migration%22,%221.1-%3Emain%22],%22snapshotName%22:%22snapshot-1697646964071%22,%22timestamp%22:1697647279704}&locales=*&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/density/1.1/wrappers/studio/?exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22density%22,%22migration%22,%221.1-%3Emain%22],%22snapshotName%22:%22snapshot-1697646964071%22,%22timestamp%22:1697647279704}&phetioDebug=false&webgl=false
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/density/1.1/density_all_phet-io.html?postMessageOnError&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22density%22,%22migration%22,%221.1-%3Emain%22],%22snapshotName%22:%22snapshot-1697646964071%22,%22timestamp%22:1697647279704}&phetioDebug=false&webgl=false&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] WebGL: INVALID_OPERATION: useProgram: program not valid
[CONSOLE] WebGL: INVALID_OPERATION: useProgram: program not valid
[CONSOLE] WebGL: INVALID_OPERATION: useProgram: program not valid
[CONSOLE] WebGL: INVALID_OPERATION: useProgram: program not valid
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: INVALID_OPERATION: useProgram: program not valid
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: INVALID_OPERATION: useProgram: program not valid
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: INVALID_OPERATION: useProgram: program not valid
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: INVALID_OPERATION: useProgram: program not valid
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: INVALID_OPERATION: useProgram: program not valid
[CONSOLE] WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
[CONSOLE] WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
[CONSOLE] WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
[CONSOLE] WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
[CONSOLE] WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost
[CONSOLE] THREE.WebGLRenderer: Context Lost.
[CONSOLE] THREE.WebGLRenderer: Context Lost.
[CONSOLE] THREE.WebGLRenderer: Context Lost.
[CONSOLE] continuous-test-wrapper-load
[NAVIGATED] https://phet-io.colorado.edu/sims/density/1.1/density_all_phet-io.html?postMessageOnError&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22density%22,%22migration%22,%221.1-%3Emain%22],%22snapshotName%22:%22snapshot-1697646964071%22,%22timestamp%22:1697647279704}&phetioDebug=false&webgl=false&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[PAGE ERROR] Error: TypeError: Cannot read properties of null (reading 'hasOwnProperty')
at https://phet-io.colorado.edu/sims/density/1.1/density_all_phet-io.html?postMessageOnError&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22density%22,%22migration%22,%221.1-%3Emain%22],%22snapshotName%22:%22snapshot-1697646964071%22,%22timestamp%22:1697647279704}&phetioDebug=false&webgl=false&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false:1070:309280
at https://phet-io.colorado.edu/sims/density/1.1/density_all_phet-io.html?postMessageOnError&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22density%22,%22migration%22,%221.1-%3Emain%22],%22snapshotName%22:%22snapshot-1697646964071%22,%22timestamp%22:1697647279704}&phetioDebug=false&webgl=false&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false:1047:47182
at Be (https://phet-io.colorado.edu/sims/density/1.1/density_all_phet-io.html?postMessageOnError&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22density%22,%22migration%22,%221.1-%3Emain%22],%22snapshotName%22:%22snapshot-1697646964071%22,%22timestamp%22:1697647279704}&phetioDebug=false&webgl=false&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false:1047:22975)
at Function.zf [as pickBy] (https://phet-io.colorado.edu/sims/density/1.1/density_all_phet-io.html?postMessageOnError&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22density%22,%22migration%22,%221.1-%3Emain%22],%22snapshotName%22:%22snapshot-1697646964071%22,%22timestamp%22:1697647279704}&phetioDebug=false&webgl=false&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false:1047:47153)
at F.getChangedState (https://phet-io.colorado.edu/sims/density/1.1/density_all_phet-io.html?postMessageOnError&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22density%22,%22migration%22,%221.1-%3Emain%22],%22snapshotName%22:%22snapshot-1697646964071%22,%22timestamp%22:1697647279704}&phetioDebug=false&webgl=false&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false:1070:309245)
at Y.implementation (https://phet-io.colorado.edu/sims/density/1.1/density_all_phet-io.html?postMessageOnError&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22density%22,%22migration%22,%221.1-%3Emain%22],%22snapshotName%22:%22snapshot-1697646964071%22,%22timestamp%22:1697647279704}&phetioDebug=false&webgl=false&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false:1070:325601)
at L.processCommand (https://phet-io.colorado.edu/sims/density/1.1/density_all_phet-io.html?postMessageOnError&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22density%22,%22migration%22,%221.1-%3Emain%22],%22snapshotName%22:%22snapshot-1697646964071%22,%22timestamp%22:1697647279704}&phetioDebug=false&webgl=false&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false:1070:306292)
at n (https://phet-io.colorado.edu/sims/density/1.1/density_all_phet-io.html?postMessageOnError&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22density%22,%22migration%22,%221.1-%3Emain%22],%22snapshotName%22:%22snapshot-1697646964071%22,%22timestamp%22:1697647279704}&phetioDebug=false&webgl=false&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false:1070:304762)
at https://phet-io.colorado.edu/sims/density/1.1/density_all_phet-io.html?postMessageOnError&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22density%22,%22migration%22,%221.1-%3Emain%22],%22snapshotName%22:%22snapshot-1697646964071%22,%22timestamp%22:1697647279704}&phetioDebug=false&webgl=false&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false:1070:304860
at Array.map (<anonymous>)
[CONSOLE] Assertion failed: never heard back from upstream sim, likely there was a problem getting state.
[PAGE ERROR] Error: Error: Assertion failed: never heard back from upstream sim, likely there was a problem getting state.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1697646964071/assert/js/assert.js:28:13)
at http://128.138.93.172/continuous-testing/ct-snapshots/1697646964071/phet-io-wrappers/migration/migration.js:221:23
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 10/18/2023, 10:36:04 AM
```

**Comment by zepumph** [comment]
CT has been clear for the last 30 hours. I'll reopen if this comes back to us.
