### ISSUE TITLE
CT MigrationReport problem: initialStatesAreIncompatible

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#191]
```
density : migration : 1.1->main : assert
http://128.138.93.172/continuous-testing/ct-snapshots/1709938245145/phet-io-wrappers/migration/?sim=density&oldVersion=1.1&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22density%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1709938245145%22%2C%22timestamp%22%3A1709938915514%7D
Assertion failed: MigrationReport problem: initialStatesAreIncompatible

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [
{
"phetioID": "density.introScreen.view.blockAControlPanel.comboBox.listBox.brickItem",
"migratedInitialState": {
"index": 3
},
"newInitialState": {
"index": 4
}
},
{
"phetioID": "density.introScreen.view.blockAControlPanel.comboBox.listBox.aluminumItem",
"migratedInitialState": {
"index": 4
},
"newInitialState": {
"index": 5
}
},
{
"phetioID": "density.introScreen.view.blockAControlPanel.comboBox.listBox.customItem",
"migratedInitialState": {
"index": 5
},
"newInitialState": {
"index": 6
}
},
{
"phetioID": "density.introScreen.view.blockBControlPanel.comboBox.listBox.brickItem",
"migratedInitialState": {
"index": 3
},
"newInitialState": {
"index": 4
}
},
{
"phetioID": "density.introScreen.view.blockBControlPanel.comboBox.listBox.aluminumItem",
"migratedInitialState": {
"index": 4
},
"newInitialState": {
"index": 5
}
},
{
"phetioID": "density.introScreen.view.blockBControlPanel.comboBox.listBox.customItem",
"migratedInitialState": {
"index": 5
},
"newInitialState": {
"index": 6
}
}
],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": []
}
[object Object]
Error: Assertion failed: MigrationReport problem: initialStatesAreIncompatible
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709938245145/assert/js/assert.js:28:13)
at assert (MigrationReport.ts:164:22)
at reportForContext (MigrationEngine.ts:86:22)
at migrate (StandardPhetioWrapper.ts:281:37)
at async (http://128.138.93.172/continuous-testing/ct-snapshots/1709938245145/phet-io-wrappers/migration/migration.js:220:11)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1709938245145%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Ddensity%26oldVersion%3D1.1%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22density%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1709938245145%22%2C%22timestamp%22%3A1709938915514%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1709938245145%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Ddensity%26oldVersion%3D1.1%26phetioMigrationReport%3Dassert%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26migrationRate%3D5000%26&duration=80000&testInfo=%7B%22test%22%3A%5B%22density%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1709938245145%22%2C%22timestamp%22%3A1709938915514%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1709938245145/phet-io-wrappers/migration/?sim=density&oldVersion=1.1&phetioMigrationReport=assert&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&migrationRate=5000&&wrapperContinuousTest=%7B%22test%22%3A%5B%22density%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1709938245145%22%2C%22timestamp%22%3A1709938915514%7D
[ATTACHED]
[NAVIGATED] about:blank
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1709938245145/studio/?sim=density&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22density%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1709938245145%22%2C%22timestamp%22%3A1709938915514%7D&phetioMigrationReport=assert&fuzz&webgl=false&locales=*
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1709938245145/density/density_en.html?brand=phet-io&ea&postMessageOnError&sim=density&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22density%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1709938245145%22%2C%22timestamp%22%3A1709938915514%7D&phetioMigrationReport=assert&fuzz&webgl=false&locales=*&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/density/1.1/wrappers/studio/?phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22density%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1709938245145%22%2C%22timestamp%22%3A1709938915514%7D&phetioMigrationReport=assert&fuzz&webgl=false&exposeStandardPhetioWrapper&phetioDebug=false
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/density/1.1/density_all_phet-io.html?postMessageOnError&phetioWrapperDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22density%22%2C%22migration%22%2C%221.1-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1709938245145%22%2C%22timestamp%22%3A1709938915514%7D&phetioMigrationReport=assert&fuzz&webgl=false&exposeStandardPhetioWrapper&phetioDebug=false&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: MigrationReport problem: initialStatesAreIncompatible

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [
{
"phetioID": "density.introScreen.view.blockAControlPanel.comboBox.listBox.brickItem",
"migratedInitialState": {
"index": 3
},
"newInitialState": {
"index": 4
}
},
{
"phetioID": "density.introScreen.view.blockAControlPanel.comboBox.listBox.aluminumItem",
"migratedInitialState": {
"index": 4
},
"newInitialState": {
"index": 5
}
},
{
"phetioID": "density.introScreen.view.blockAControlPanel.comboBox.listBox.customItem",
"migratedInitialState": {
"index": 5
},
"newInitialState": {
"index": 6
}
},
{
"phetioID": "density.introScreen.view.blockBControlPanel.comboBox.listBox.brickItem",
"migratedInitialState": {
"index": 3
},
"newInitialState": {
"index": 4
}
},
{
"phetioID": "density.introScreen.view.blockBControlPanel.comboBox.listBox.aluminumItem",
"migratedInitialState": {
"index": 4
},
"newInitialState": {
"index": 5
}
},
{
"phetioID": "density.introScreen.view.blockBControlPanel.comboBox.listBox.customItem",
"migratedInitialState": {
"index": 5
},
"newInitialState": {
"index": 6
}
}
],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": []
} JSHandle@object
[PAGE ERROR] Error: Error: Assertion failed: MigrationReport problem: initialStatesAreIncompatible

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [
{
"phetioID": "density.introScreen.view.blockAControlPanel.comboBox.listBox.brickItem",
"migratedInitialState": {
"index": 3
},
"newInitialState": {
"index": 4
}
},
{
"phetioID": "density.introScreen.view.blockAControlPanel.comboBox.listBox.aluminumItem",
"migratedInitialState": {
"index": 4
},
"newInitialState": {
"index": 5
}
},
{
"phetioID": "density.introScreen.view.blockAControlPanel.comboBox.listBox.customItem",
"migratedInitialState": {
"index": 5
},
"newInitialState": {
"index": 6
}
},
{
"phetioID": "density.introScreen.view.blockBControlPanel.comboBox.listBox.brickItem",
"migratedInitialState": {
"index": 3
},
"newInitialState": {
"index": 4
}
},
{
"phetioID": "density.introScreen.view.blockBControlPanel.comboBox.listBox.aluminumItem",
"migratedInitialState": {
"index": 4
},
"newInitialState": {
"index": 5
}
},
{
"phetioID": "density.introScreen.view.blockBControlPanel.comboBox.listBox.customItem",
"migratedInitialState": {
"index": 5
},
"newInitialState": {
"index": 6
}
}
],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": []
}
[object Object]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1709938245145/assert/js/assert.js:28:13)
at MigrationReport.reportForContext (http://128.138.93.172/continuous-testing/ct-snapshots/1709938245145/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationReport.js:141:23)
at MigrationEngine.migrate (http://128.138.93.172/continuous-testing/ct-snapshots/1709938245145/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationEngine.js:65:23)
at StandardPhetioWrapper.loadStandardPhetioWrapperFromHTML (http://128.138.93.172/continuous-testing/ct-snapshots/1709938245145/chipper/dist/js/phet-io-wrappers/common/js/StandardPhetioWrapper.js:199:38)
at async http://128.138.93.172/continuous-testing/ct-snapshots/1709938245145/phet-io-wrappers/migration/migration.js:220:11
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 3/8/2024, 3:50:45 PM
```

**Comment by zepumph** [comment]
Fixed in https://github.com/phetsims/density/issues/192.
