### ISSUE TITLE
CT false is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#2]
Already documented in https://github.com/phetsims/buoyancy/issues/2, but replicating here for this sim
```
density : fuzz : built : load
Query: fuzz&memoryLimit=1000
Uncaught TypeError: false is not a function
TypeError: false is not a function
    at new t (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/build/phet/density_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1060:406996)
    at i._possibleConstructorReturn.call.name [as createModel] (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/build/phet/density_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1060:924496)
    at initializeModel (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/build/phet/density_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1060:909360)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/build/phet/density_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1060:1118559)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/build/phet/density_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1060:1118676
id: Bayes Chrome
Approximately 5/14/2019, 2:33:07 AM
density : fuzz : built : run
Query: fuzz&memoryLimit=1000
Uncaught TypeError: false is not a function
TypeError: false is not a function
    at new t (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/build/phet/density_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1060:406996)
    at i._possibleConstructorReturn.call.name [as createModel] (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/build/phet/density_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1060:924496)
    at initializeModel (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/build/phet/density_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1060:909360)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/build/phet/density_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1060:1118559)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/build/phet/density_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1060:1118676
id: Bayes Chrome
Approximately 5/14/2019, 2:33:07 AM
density : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/sherpa/lib/three-r104.js:22839:12)
    at new MobiusSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/mobius/js/MobiusSceneNode.js?bust=1557828735485:61:28)
    at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js?bust=1557828735485:32:24)
    at ComparingScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/js/view/ComparingScreen.js?bust=1557828735485:28:18)
    at ComparingScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Screen.js?bust=1557828735485:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557828735485:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557828735485:811:27
id: Bayes Chrome
Approximately 5/14/2019, 2:33:07 AM
density : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/sherpa/lib/three-r104.js:22839:12)
    at new MobiusSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/mobius/js/MobiusSceneNode.js?bust=1557828735485:61:28)
    at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js?bust=1557828735485:32:24)
    at ComparingScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/js/view/ComparingScreen.js?bust=1557828735485:28:18)
    at ComparingScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Screen.js?bust=1557828735485:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557828735485:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557828735485:811:27
id: Bayes Chrome
Approximately 5/14/2019, 2:33:07 AM
density : fuzz : require.js-canvas : load
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/sherpa/lib/three-r104.js:22839:12)
    at new MobiusSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/mobius/js/MobiusSceneNode.js?bust=1557827564963:61:28)
    at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js?bust=1557827564963:32:24)
    at ComparingScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/js/view/ComparingScreen.js?bust=1557827564963:28:18)
    at ComparingScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Screen.js?bust=1557827564963:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557827564963:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557827564963:811:27
id: Bayes Chrome
Approximately 5/14/2019, 2:33:07 AM
density : fuzz : require.js-canvas : load
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/sherpa/lib/three-r104.js:22839:12)
    at new MobiusSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/mobius/js/MobiusSceneNode.js?bust=1557837872576:61:28)
    at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js?bust=1557837872576:32:24)
    at ComparingScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/js/view/ComparingScreen.js?bust=1557837872576:28:18)
    at ComparingScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Screen.js?bust=1557837872576:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557837872576:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557837872576:811:27
id: Bayes Chrome
Approximately 5/14/2019, 2:33:07 AM
density : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/sherpa/lib/three-r104.js:22839:12)
    at new MobiusSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/mobius/js/MobiusSceneNode.js?bust=1557827564963:61:28)
    at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js?bust=1557827564963:32:24)
    at ComparingScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/js/view/ComparingScreen.js?bust=1557827564963:28:18)
    at ComparingScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Screen.js?bust=1557827564963:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557827564963:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557827564963:811:27
id: Bayes Chrome
Approximately 5/14/2019, 2:33:07 AM
density : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/sherpa/lib/three-r104.js:22839:12)
    at new MobiusSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/mobius/js/MobiusSceneNode.js?bust=1557837872576:61:28)
    at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js?bust=1557837872576:32:24)
    at ComparingScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/js/view/ComparingScreen.js?bust=1557837872576:28:18)
    at ComparingScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Screen.js?bust=1557837872576:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557837872576:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557837872576:811:27
id: Bayes Chrome
Approximately 5/14/2019, 2:33:07 AM
density : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/sherpa/lib/three-r104.js:22839:12)
    at new MobiusSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/mobius/js/MobiusSceneNode.js?bust=1557828106484:61:28)
    at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js?bust=1557828106484:32:24)
    at ComparingScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/js/view/ComparingScreen.js?bust=1557828106484:28:18)
    at ComparingScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Screen.js?bust=1557828106484:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557828106484:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557828106484:811:27
id: Bayes Chrome
Approximately 5/14/2019, 2:33:07 AM
density : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/sherpa/lib/three-r104.js:22839:12)
    at new MobiusSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/mobius/js/MobiusSceneNode.js?bust=1557836320775:61:28)
    at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js?bust=1557836320775:32:24)
    at ComparingScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/js/view/ComparingScreen.js?bust=1557836320775:28:18)
    at ComparingScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Screen.js?bust=1557836320775:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557836320775:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557836320775:811:27
id: Bayes Chrome
Approximately 5/14/2019, 2:33:07 AM
density : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/sherpa/lib/three-r104.js:22839:12)
    at new MobiusSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/mobius/js/MobiusSceneNode.js?bust=1557828106484:61:28)
    at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js?bust=1557828106484:32:24)
    at ComparingScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/js/view/ComparingScreen.js?bust=1557828106484:28:18)
    at ComparingScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Screen.js?bust=1557828106484:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557828106484:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557828106484:811:27
id: Bayes Chrome
Approximately 5/14/2019, 2:33:07 AM
density : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/sherpa/lib/three-r104.js:22839:12)
    at new MobiusSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/mobius/js/MobiusSceneNode.js?bust=1557836320775:61:28)
    at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js?bust=1557836320775:32:24)
    at ComparingScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/density/js/view/ComparingScreen.js?bust=1557836320775:28:18)
    at ComparingScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Screen.js?bust=1557836320775:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557836320775:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557822787421/joist/js/Sim.js?bust=1557836320775:811:27
id: Bayes Chrome
Approximately 5/14/2019, 2:33:07 AM
```

**Comment by jonathanolson** [comment]
Sorry about that! I accidentally wrote `assert` instead of `assert && assert`, and it only fails for the built form. Should be fixed in master now.
