### ISSUE TITLE
CT Error creating WebGL context

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#3]
```
density : fuzz : require.js-canvas : load
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/sherpa/lib/three-r104.js:22839:12)
    at new MobiusSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/mobius/js/MobiusSceneNode.js?bust=1557867361762:61:28)
    at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js?bust=1557867361762:32:24)
    at ComparingScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/density/js/view/ComparingScreen.js?bust=1557867361762:28:18)
    at ComparingScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/joist/js/Screen.js?bust=1557867361762:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/joist/js/Sim.js?bust=1557867361762:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/joist/js/Sim.js?bust=1557867361762:811:27
id: Bayes Chrome
Approximately 5/14/2019, 2:07:31 PM
density : fuzz : require.js-canvas : run
Query: brand=phet&ea&fuzz&rootRenderer=canvas&memoryLimit=1000
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/sherpa/lib/three-r104.js:22839:12)
    at new MobiusSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/mobius/js/MobiusSceneNode.js?bust=1557867361762:61:28)
    at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js?bust=1557867361762:32:24)
    at ComparingScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/density/js/view/ComparingScreen.js?bust=1557867361762:28:18)
    at ComparingScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/joist/js/Screen.js?bust=1557867361762:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/joist/js/Sim.js?bust=1557867361762:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/joist/js/Sim.js?bust=1557867361762:811:27
id: Bayes Chrome
Approximately 5/14/2019, 2:07:31 PM
density : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/sherpa/lib/three-r104.js:22839:12)
    at new MobiusSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/mobius/js/MobiusSceneNode.js?bust=1557867361762:61:28)
    at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js?bust=1557867361762:32:24)
    at ComparingScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/density/js/view/ComparingScreen.js?bust=1557867361762:28:18)
    at ComparingScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/joist/js/Screen.js?bust=1557867361762:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/joist/js/Sim.js?bust=1557867361762:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/joist/js/Sim.js?bust=1557867361762:811:27
id: Bayes Chrome
Approximately 5/14/2019, 2:07:31 PM
density : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
    at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/sherpa/lib/three-r104.js:22839:12)
    at new MobiusSceneNode (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/mobius/js/MobiusSceneNode.js?bust=1557867361762:61:28)
    at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js?bust=1557867361762:32:24)
    at ComparingScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/density/js/view/ComparingScreen.js?bust=1557867361762:28:18)
    at ComparingScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/joist/js/Screen.js?bust=1557867361762:261:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/joist/js/Sim.js?bust=1557867361762:803:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1557864451439/joist/js/Sim.js?bust=1557867361762:811:27
id: Bayes Chrome
Approximately 5/14/2019, 2:07:31 PM
```

**Comment by jonathanolson** [comment]
I believe this should be fixed.
