### ISSUE TITLE
CT build failed with status code 1

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/density#83]
```
density : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (density, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 5680ms
>> Production minification complete: 43962ms (3458296 bytes)
>> Debug minification complete: 1ms (8985429 bytes)
Building brand: phet-io
>> Webpack build complete: 4012ms
>> Production minification complete: 39503ms (3484773 bytes)
>> Debug minification complete: 38965ms (3770516 bytes)
>> No client guides found at ../phet-io-client-guides/density/, no guides being built.
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1629395879601/chipper/js/grunt/copySupplementalPhetioFiles.js:316:5)
at async module.exports (/data/share/phet/continuous-testing/ct-snapshots/1629395879601/chipper/js/grunt/buildRunnable.js:356:5)
at async /data/share/phet/continuous-testing/ct-snapshots/1629395879601/chipper/js/grunt/Gruntfile.js:254:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1629395879601/chipper/js/grunt/Gruntfile.js:71:7)
Full Error details:
AssertionError [ERR_ASSERTION]: Full API expected but not created from puppeteer step, likely caused by https://github.com/phetsims/chipper/issues/1022.

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Error in fulfilling chunk Promise: [Error: TypeError: Cannot read properties of undefined (reading 'createTandem')
at new lk (http://localhost:46411/density/build/phet-io/density_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:1172:2321107)
at Ek.createModel (http://localhost:46411/density/build/phet-io/density_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:1172:2342686)
at Ek.initializeModel (http://localhost:46411/density/build/phet-io/density_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:1172:870817)
at Array.<anonymous> (http://localhost:46411/density/build/phet-io/density_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:1172:1150483)
at http://localhost:46411/density/build/phet-io/density_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI&randomSeed=332211:1172:1150670]
Snapshot from 8/19/2021, 11:57:59 AM

----------------------------------

density : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629395879601%22%2C%22timestamp%22%3A1629398346607%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new DensityIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density-buoyancy-common/js/density/model/DensityIntroModel.js:37:35)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density/js/intro/IntroScreen.js:31:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:944:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:955:25
id: Bayes Chrome
Snapshot from 8/19/2021, 11:57:59 AM

----------------------------------

density : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629395879601%22%2C%22timestamp%22%3A1629396888135%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new DensityIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density-buoyancy-common/js/density/model/DensityIntroModel.js:37:35)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density/js/intro/IntroScreen.js:31:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:944:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:955:25
id: Bayes Chrome
Snapshot from 8/19/2021, 11:57:59 AM

----------------------------------

density : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629395879601%22%2C%22timestamp%22%3A1629397650735%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new DensityIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density-buoyancy-common/js/density/model/DensityIntroModel.js:37:35)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density/js/intro/IntroScreen.js:31:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:944:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:955:25
id: Bayes Chrome
Snapshot from 8/19/2021, 11:57:59 AM

----------------------------------

density : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629395879601%22%2C%22timestamp%22%3A1629397389942%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new DensityIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density-buoyancy-common/js/density/model/DensityIntroModel.js:37:35)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density/js/intro/IntroScreen.js:31:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:944:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:955:25
id: Bayes Chrome
Snapshot from 8/19/2021, 11:57:59 AM

----------------------------------

density : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/phet-io-wrappers/mirror-inputs/?sim=density&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629395879601%22%2C%22timestamp%22%3A1629398082818%7D
Uncaught Error: Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new DensityIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density-buoyancy-common/js/density/model/DensityIntroModel.js:37:35)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density/js/intro/IntroScreen.js:31:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:944:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:955:25
id: Bayes Chrome
Snapshot from 8/19/2021, 11:57:59 AM

----------------------------------

density : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/phet-io-wrappers/state/?sim=density&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1629395879601%22%2C%22timestamp%22%3A1629399830816%7D
Uncaught Error: Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new DensityIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density-buoyancy-common/js/density/model/DensityIntroModel.js:37:35)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density/js/intro/IntroScreen.js:31:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:944:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:955:25
id: Bayes Chrome
Snapshot from 8/19/2021, 11:57:59 AM

----------------------------------

density : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/phet-io-wrappers/phet-io-wrappers-tests.html?sim=density&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: density: iframe API failed:
Uncaught Error: Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new DensityIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density-buoyancy-common/js/density/model/DensityIntroModel.js:37:35)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density/js/intro/IntroScreen.js:31:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:944:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:955:25

Uncaught Error: Uncaught TypeError: Cannot read property 'createTandem' of undefinedTypeError: Cannot read property 'createTandem' of undefined
at new DensityIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density-buoyancy-common/js/density/model/DensityIntroModel.js:37:35)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density/js/intro/IntroScreen.js:31:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:944:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:955:25
id: Bayes Chrome
Snapshot from 8/19/2021, 11:57:59 AM

----------------------------------

density : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1629395879601%22%2C%22timestamp%22%3A1629397354198%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: Cannot read property 'createTandem' of undefined
TypeError: Cannot read property 'createTandem' of undefined
at new DensityIntroModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density-buoyancy-common/js/density/model/DensityIntroModel.js:37:35)
at IntroScreen.createModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/density/js/intro/IntroScreen.js:31:13)
at IntroScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Screen.js:240:24)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:944:16)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1629395879601/joist/js/Sim.js:955:25
id: Bayes Chrome
Snapshot from 8/19/2021, 11:57:59 AM
```

**Comment by jonathanolson** [comment]
I believe I resolved this, it was commits that I had failed to push from density/buoyancy themselves.

**Comment by KatieWoe** [comment]
Not sure if this is related:
```
density : build
Build failed with status code 3:
Running "report-media" task

Running "clean" task

Running "build" task
>> TypeScript compilation complete: 3170ms
Building runnable repository (density, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 5957ms
>> Production minification complete: 43186ms (3553645 bytes)
>> Debug minification complete: 1ms (9671182 bytes)
Building brand: phet-io
>> Webpack build complete: 4368ms
>> Production minification complete: 40724ms (3606911 bytes)
>> Debug minification complete: 38721ms (3898286 bytes)
>> No client guides found at ../phet-io-client-guides/density/, no guides being built.
>> TypeScript compilation complete: 3515ms
Fatal error: Protocol error: Connection closed. Most likely the page has been closed.
Snapshot from 11/23/2021, 8:33:34 AM

----------------------------------

density : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/density/density_en.html?continuousTest=%7B%22test%22%3A%5B%22density%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1637681614091%22%2C%22timestamp%22%3A1637683545129%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Error creating WebGL context.
Error: Error creating WebGL context.
at new WebGLRenderer (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/sherpa/lib/three-r104.js:22839:12)
at new ThreeStage (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/mobius/js/ThreeStage.js:47:30)
at new ThreeIsometricNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/mobius/js/ThreeIsometricNode.js:37:22)
at new DensityBuoyancyScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/density-buoyancy-common/js/common/view/DensityBuoyancyScreenView.js:113:26)
at new SecondaryMassScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/density-buoyancy-common/js/common/view/SecondaryMassScreenView.js:11:1)
at new DensityIntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/density-buoyancy-common/js/density/view/DensityIntroScreenView.js:28:9)
at IntroScreen.name [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/density/js/intro/IntroScreen.js:27:22)
at IntroScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/joist/js/Screen.js:206:27)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/joist/js/Sim.js:609:24)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1637681614091/chipper/dist/joist/js/Sim.js:616:29
id: Bayes Chrome
Snapshot from 11/23/2021, 8:33:34 AM
```

**Comment by jonathanolson** [comment]
I'm not seeing this continue, and I can't reproduce. Thoughts? Good to close?

**Comment by KatieWoe** [comment]
We can close. If I see it again I'll reopen.
